# Theme Check Configuration
# https://shopify.dev/docs/storefronts/themes/tools/theme-check

# Enable recommended checks
MatchingTranslations:
  enabled: true

TemplateLength:
  enabled: true
  max_length: 600

MissingTemplate:
  enabled: true

UnusedAssign:
  enabled: true

# Asset size limits
AssetSizeCss:
  enabled: true
  threshold_in_bytes: 150000

AssetSizeJavaScript:
  enabled: true
  threshold_in_bytes: 300000

# Syntax validation
LiquidTag:
  enabled: true

ValidJson:
  enabled: true

# Image optimization checks
ImgLazyLoading:
  enabled: true

ImgWidthAndHeight:
  enabled: true

# Accessibility checks
RequiredLayoutThemeObject:
  enabled: true

# SEO checks
RequiredMetaTags:
  enabled: true

# Performance
ParserBlockingJavaScript:
  enabled: true

# Keep disabled - we use external CDNs intentionally (Leaflet, etc.)
RemoteAsset:
  enabled: false

# Keep disabled - handled by build tools
AssetUrlFilters:
  enabled: false
